### ISSUE TITLE
underscore in sample name

### ISSUE THREAD

**Issue by hreypar** [Gabrielstav/HiEdge#1]
Hi, I think sample names **cannot** have underscore (`_`) in their name. There's probably a line somewhere separating the sample name from the resolution and file extension using the underscore 

e.g. separating `MCF7_rep1_GSM4097072` from `40000.matrix` in `MCF7_rep1_GSM4097072_40000.matrix` 

The point is that the regex there should probably be indicating the last underscore, and it might not do that now, so if the sample names have it, HiEdge won't find anything. 

I'd help fix it but I'm in a race against time right now, sorry :( 

PS. Thanks for HiEdge! saving me lots of time, do you have a DOI?

**Comment by Gabrielstav** [comment]
Hi @hreypar, thanks for opening an issue! 

You are correct that the regex used to match input files on resolution and experiment (i.e. HiC-Pro run name) was not robust to different file names, e.g. if a number was adjacent to an underscore in the experiment name. This is fixed now :) 


I'm glad to hear it, I added the DOI for the project in the readme now (10.5281/zenodo.13357276).
